#pragma once

#include <ntddk.h>
#include <wdf.h>

#define SEC_AI_DEVICE_TYPE 40000

// Define the IOCTL codes for communication between User-Mode Python / C++ Bridge and the Kernel Driver
#define IOCTL_START_CAPTURE \
    CTL_CODE(SEC_AI_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_STOP_CAPTURE \
    CTL_CODE(SEC_AI_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_ADD_BLOCK_RULE \
    CTL_CODE(SEC_AI_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_REMOVE_BLOCK_RULE \
    CTL_CODE(SEC_AI_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GET_STATS \
    CTL_CODE(SEC_AI_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
